### ISSUE TITLE
🐛Line appearing between NavigationBar and segments

### ISSUE THREAD

**Issue by HugoPrinsloo** [HugoPrinsloo/Cards#1]
<img width="545" alt="screenshot 2018-07-07 at 11 19 21" src="https://user-images.githubusercontent.com/12765774/42409282-60c0f6da-81d8-11e8-85f3-29dcf01a2be4.png">

**Comment by AntonOnyH** [comment]
Closing this issue - https://github.com/HugoPrinsloo/Cards/issues/19 - new feature will take care of this aotomaticly
